import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface CaptionTrack {
  id: string
  language: string
  languageName: string
  kind: 'asr' | 'standard'
  isDefault: boolean
}

interface TranscriptionResult {
  text: string
  language: string
  languageName: string
  isAutoGenerated: boolean
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    // Verify authentication
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized', code: 'UNAUTHORIZED' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_ANON_KEY') ?? '',
      { global: { headers: { Authorization: authHeader } } }
    )

    const { data: { user }, error: authError } = await supabaseClient.auth.getUser()
    if (authError || !user) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized', code: 'UNAUTHORIZED' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Parse request body
    const { videoId, action, languageCode } = await req.json()

    if (!videoId || typeof videoId !== 'string') {
      return new Response(
        JSON.stringify({ error: 'videoId is required', code: 'INVALID_REQUEST' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Validate videoId format
    if (!/^[a-zA-Z0-9_-]{11}$/.test(videoId)) {
      return new Response(
        JSON.stringify({ error: 'Invalid videoId format', code: 'INVALID_VIDEO_ID' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const youtubeApiKey = Deno.env.get('YOUTUBE_API_KEY')
    if (!youtubeApiKey) {
      return new Response(
        JSON.stringify({ error: 'YouTube API not configured', code: 'NOT_CONFIGURED' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Action: list - Get available caption tracks
    if (action === 'list' || !action) {
      const tracks = await listCaptionTracks(videoId, youtubeApiKey)
      return new Response(
        JSON.stringify({ tracks }),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // Action: get - Get transcription for a specific language
    if (action === 'get') {
      const transcription = await getTranscription(videoId, languageCode)
      return new Response(
        JSON.stringify(transcription),
        { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    return new Response(
      JSON.stringify({ error: 'Invalid action', code: 'INVALID_ACTION' }),
      { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error) {
    console.error('Error in youtube-captions function:', error)

    // Check for specific error types
    const errorMessage = error instanceof Error ? error.message : 'Unknown error'

    if (errorMessage.includes('NO_CAPTIONS')) {
      return new Response(
        JSON.stringify({ error: 'No captions available for this video', code: 'NO_CAPTIONS' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    return new Response(
      JSON.stringify({
        error: 'Internal server error',
        code: 'INTERNAL_ERROR',
        details: errorMessage
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})

/**
 * List available caption tracks using YouTube Data API
 */
async function listCaptionTracks(videoId: string, apiKey: string): Promise<CaptionTrack[]> {
  const apiUrl = new URL('https://www.googleapis.com/youtube/v3/captions')
  apiUrl.searchParams.set('part', 'snippet')
  apiUrl.searchParams.set('videoId', videoId)
  apiUrl.searchParams.set('key', apiKey)

  const response = await fetch(apiUrl.toString())
  const data = await response.json()

  if (!response.ok) {
    console.error('YouTube Captions API error:', data)
    if (data.error?.errors?.[0]?.reason === 'forbidden') {
      // If captions API is forbidden, try alternative method
      return await listCaptionsAlternative(videoId)
    }
    throw new Error(`YouTube API error: ${data.error?.message || 'Unknown error'}`)
  }

  if (!data.items || data.items.length === 0) {
    // Try alternative method
    return await listCaptionsAlternative(videoId)
  }

  return data.items.map((item: any) => ({
    id: item.id,
    language: item.snippet.language,
    languageName: item.snippet.name || getLanguageName(item.snippet.language),
    kind: item.snippet.trackKind === 'ASR' ? 'asr' : 'standard',
    isDefault: item.snippet.isDefault || false,
  }))
}

/**
 * Alternative method to get captions using the timedtext API
 * This works for auto-generated captions which the main API doesn't always return
 */
async function listCaptionsAlternative(videoId: string): Promise<CaptionTrack[]> {
  // Try to fetch the video page to get caption info
  const watchUrl = `https://www.youtube.com/watch?v=${videoId}`
  const response = await fetch(watchUrl)
  const html = await response.text()

  // Extract caption tracks from the page
  const captionTracksMatch = html.match(/"captionTracks":(\[.*?\])/)
  if (!captionTracksMatch) {
    throw new Error('NO_CAPTIONS: No caption tracks found')
  }

  try {
    const captionTracks = JSON.parse(captionTracksMatch[1])
    return captionTracks.map((track: any) => ({
      id: track.vssId || track.languageCode,
      language: track.languageCode,
      languageName: track.name?.simpleText || getLanguageName(track.languageCode),
      kind: track.kind === 'asr' ? 'asr' : 'standard',
      isDefault: track.languageCode === 'en' || captionTracks.length === 1,
    }))
  } catch {
    throw new Error('NO_CAPTIONS: Failed to parse caption tracks')
  }
}

/**
 * Get transcription text using the timedtext API
 */
async function getTranscription(videoId: string, languageCode?: string): Promise<TranscriptionResult> {
  // First, get the video page to extract caption URL
  const watchUrl = `https://www.youtube.com/watch?v=${videoId}`
  const response = await fetch(watchUrl)
  const html = await response.text()

  // Extract caption tracks from the page
  const captionTracksMatch = html.match(/"captionTracks":(\[.*?\])/)
  if (!captionTracksMatch) {
    throw new Error('NO_CAPTIONS: No caption tracks found')
  }

  let captionTracks: any[]
  try {
    captionTracks = JSON.parse(captionTracksMatch[1])
  } catch {
    throw new Error('NO_CAPTIONS: Failed to parse caption tracks')
  }

  if (captionTracks.length === 0) {
    throw new Error('NO_CAPTIONS: No caption tracks available')
  }

  // Find the requested language or use the first available
  let selectedTrack = captionTracks[0]
  if (languageCode) {
    const found = captionTracks.find(
      (track: any) => track.languageCode === languageCode || track.vssId === languageCode
    )
    if (found) {
      selectedTrack = found
    }
  }

  // Fetch the caption content
  let captionUrl = selectedTrack.baseUrl
  if (!captionUrl) {
    throw new Error('NO_CAPTIONS: No caption URL found')
  }

  // Request plain text format
  captionUrl += '&fmt=srv3'

  const captionResponse = await fetch(captionUrl)
  const captionXml = await captionResponse.text()

  // Parse the XML transcript
  const text = parseTranscriptXml(captionXml)

  return {
    text,
    language: selectedTrack.languageCode,
    languageName: selectedTrack.name?.simpleText || getLanguageName(selectedTrack.languageCode),
    isAutoGenerated: selectedTrack.kind === 'asr',
  }
}

/**
 * Parse YouTube transcript XML format
 */
function parseTranscriptXml(xml: string): string {
  const textMatches = xml.matchAll(/<text[^>]*>(.*?)<\/text>/gs)
  const segments: string[] = []

  for (const match of textMatches) {
    let text = match[1]
    // Decode HTML entities
    text = text
      .replace(/&amp;/g, '&')
      .replace(/&lt;/g, '<')
      .replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"')
      .replace(/&#39;/g, "'")
      .replace(/\n/g, ' ')
      .trim()

    if (text) {
      segments.push(text)
    }
  }

  // Join segments with spaces and clean up
  return segments
    .join(' ')
    .replace(/\s+/g, ' ')
    .trim()
}

/**
 * Get human-readable language name from code
 */
function getLanguageName(code: string): string {
  const languages: Record<string, string> = {
    en: 'English',
    es: 'Spanish',
    pt: 'Portuguese',
    fr: 'French',
    de: 'German',
    it: 'Italian',
    ja: 'Japanese',
    ko: 'Korean',
    zh: 'Chinese',
    ru: 'Russian',
    ar: 'Arabic',
    hi: 'Hindi',
    'en-US': 'English (US)',
    'en-GB': 'English (UK)',
    'es-ES': 'Spanish (Spain)',
    'es-MX': 'Spanish (Mexico)',
    'pt-BR': 'Portuguese (Brazil)',
    'zh-CN': 'Chinese (Simplified)',
    'zh-TW': 'Chinese (Traditional)',
  }
  return languages[code] || code
}
