import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest'
import {
  isYouTubeImportAvailable,
  getVideoMetadata,
  getCaptionTracks,
  getTranscription,
  summarizeTranscription,
  importFromYouTube,
  YouTubeService,
} from '../YouTubeService'

// Mock fetch globally
const mockFetch = vi.fn()
vi.stubGlobal('fetch', mockFetch)

describe('YouTubeService', () => {
  beforeEach(() => {
    mockFetch.mockReset()
    vi.spyOn(console, 'error').mockImplementation(() => {})
  })

  afterEach(() => {
    vi.restoreAllMocks()
  })

  describe('isYouTubeImportAvailable', () => {
    it('returns true', () => {
      expect(isYouTubeImportAvailable()).toBe(true)
    })

    it('is exported on YouTubeService object', () => {
      expect(YouTubeService.isAvailable()).toBe(true)
    })
  })

  describe('getVideoMetadata', () => {
    it('throws INVALID_URL for invalid YouTube URL', async () => {
      await expect(getVideoMetadata('https://example.com/video')).rejects.toMatchObject({
        code: 'INVALID_URL',
        message: 'Invalid YouTube URL',
      })
    })

    it('throws INVALID_URL when video ID cannot be extracted', async () => {
      // URL is valid domain but no video ID
      await expect(getVideoMetadata('https://youtube.com/')).rejects.toMatchObject({
        code: 'INVALID_URL',
        message: 'Could not extract video ID from URL',
      })
    })

    it('calls API with extracted video ID', async () => {
      const mockMetadata = {
        videoId: 'dQw4w9WgXcQ',
        title: 'Test Video',
        channelName: 'Test Channel',
        duration: 'PT3M30S',
      }
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(mockMetadata),
      })

      const result = await getVideoMetadata('https://www.youtube.com/watch?v=dQw4w9WgXcQ')

      expect(mockFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/youtube-metadata'),
        expect.objectContaining({
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ videoId: 'dQw4w9WgXcQ' }),
        })
      )
      expect(result).toEqual(mockMetadata)
    })

    it('handles short YouTube URLs', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ videoId: 'abc123XYZ-_' }),
      })

      await getVideoMetadata('https://youtu.be/abc123XYZ-_')

      expect(mockFetch).toHaveBeenCalledWith(
        expect.any(String),
        expect.objectContaining({
          body: JSON.stringify({ videoId: 'abc123XYZ-_' }),
        })
      )
    })

    it('throws RATE_LIMITED on 429 response', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        status: 429,
        json: () => Promise.resolve({ error: 'Too many requests' }),
      })

      await expect(getVideoMetadata('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).rejects.toMatchObject({
        code: 'RATE_LIMITED',
      })
    })

    it('throws RATE_LIMITED when response has RATE_LIMITED code', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        status: 400,
        json: () => Promise.resolve({ code: 'RATE_LIMITED', error: 'Rate limited' }),
      })

      await expect(getVideoMetadata('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).rejects.toMatchObject({
        code: 'RATE_LIMITED',
      })
    })

    it('throws error with code from response', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        status: 404,
        json: () => Promise.resolve({ code: 'VIDEO_NOT_FOUND', error: 'Video not found' }),
      })

      await expect(getVideoMetadata('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).rejects.toMatchObject({
        code: 'VIDEO_NOT_FOUND',
        message: 'Video not found',
      })
    })

    it('throws UNKNOWN_ERROR for response without code', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        status: 500,
        json: () => Promise.resolve({ error: 'Server error' }),
      })

      await expect(getVideoMetadata('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).rejects.toMatchObject({
        code: 'UNKNOWN_ERROR',
      })
    })

    it('throws NETWORK_ERROR on fetch failure', async () => {
      mockFetch.mockRejectedValueOnce(new Error('Network failure'))

      await expect(getVideoMetadata('https://www.youtube.com/watch?v=dQw4w9WgXcQ')).rejects.toMatchObject({
        code: 'NETWORK_ERROR',
        message: 'Network failure',
      })
    })
  })

  describe('getCaptionTracks', () => {
    it('returns caption tracks from API', async () => {
      const tracks = [
        { languageCode: 'en', languageName: 'English', isAutoGenerated: false },
        { languageCode: 'es', languageName: 'Spanish', isAutoGenerated: true },
      ]
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ tracks }),
      })

      const result = await getCaptionTracks('videoId123')

      expect(mockFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/youtube-captions'),
        expect.objectContaining({
          body: JSON.stringify({ videoId: 'videoId123', action: 'list' }),
        })
      )
      expect(result).toEqual(tracks)
    })

    it('returns empty array when tracks is undefined', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({}),
      })

      const result = await getCaptionTracks('videoId123')
      expect(result).toEqual([])
    })
  })

  describe('getTranscription', () => {
    it('calls API with videoId and action', async () => {
      const transcription = {
        text: 'Hello world',
        languageCode: 'en',
        languageName: 'English',
        isAutoGenerated: false,
      }
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(transcription),
      })

      const result = await getTranscription('videoId123')

      expect(mockFetch).toHaveBeenCalledWith(
        expect.any(String),
        expect.objectContaining({
          body: JSON.stringify({ videoId: 'videoId123', action: 'get', languageCode: undefined }),
        })
      )
      expect(result).toEqual(transcription)
    })

    it('passes language code when specified', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ text: 'Hola mundo' }),
      })

      await getTranscription('videoId123', 'es')

      expect(mockFetch).toHaveBeenCalledWith(
        expect.any(String),
        expect.objectContaining({
          body: JSON.stringify({ videoId: 'videoId123', action: 'get', languageCode: 'es' }),
        })
      )
    })
  })

  describe('summarizeTranscription', () => {
    it('calls API with text and default Spanish language', async () => {
      const summary = {
        summary: 'This is a summary',
        keyPoints: ['Point 1', 'Point 2'],
        topics: ['Topic A'],
      }
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve(summary),
      })

      const result = await summarizeTranscription('Long transcription text')

      expect(mockFetch).toHaveBeenCalledWith(
        expect.stringContaining('/api/summarize'),
        expect.objectContaining({
          body: JSON.stringify({
            text: 'Long transcription text',
            videoTitle: undefined,
            language: 'es',
          }),
        })
      )
      expect(result).toEqual(summary)
    })

    it('passes video title when provided', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: () => Promise.resolve({ summary: 'Summary' }),
      })

      await summarizeTranscription('Text', 'Video Title', 'en')

      expect(mockFetch).toHaveBeenCalledWith(
        expect.any(String),
        expect.objectContaining({
          body: JSON.stringify({
            text: 'Text',
            videoTitle: 'Video Title',
            language: 'en',
          }),
        })
      )
    })
  })

  describe('importFromYouTube', () => {
    // YouTube video IDs are exactly 11 characters
    const validVideoId = 'dQw4w9WgXcQ'
    const mockMetadata = {
      videoId: validVideoId,
      title: 'Test Video',
      channelName: 'Test Channel',
      duration: 'PT5M',
    }
    const mockTranscription = {
      text: 'Transcription text',
      languageCode: 'en',
      languageName: 'English',
      isAutoGenerated: false,
    }
    const mockSummary = {
      summary: 'Summary',
      keyPoints: [],
      topics: [],
    }

    it('returns metadata and transcription without summary by default', async () => {
      mockFetch
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockMetadata),
        })
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockTranscription),
        })

      const result = await importFromYouTube(`https://www.youtube.com/watch?v=${validVideoId}`)

      expect(result).toEqual({
        metadata: mockMetadata,
        transcription: mockTranscription,
        summary: undefined,
      })
      expect(mockFetch).toHaveBeenCalledTimes(2)
    })

    it('includes summary when includeSummary is true', async () => {
      mockFetch
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockMetadata),
        })
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockTranscription),
        })
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockSummary),
        })

      const result = await importFromYouTube(`https://www.youtube.com/watch?v=${validVideoId}`, {
        includeSummary: true,
      })

      expect(result.summary).toEqual(mockSummary)
      expect(mockFetch).toHaveBeenCalledTimes(3)
    })

    it('passes caption language to transcription request', async () => {
      mockFetch
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockMetadata),
        })
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockTranscription),
        })

      await importFromYouTube(`https://www.youtube.com/watch?v=${validVideoId}`, {
        captionLanguage: 'es',
      })

      // Second call is getTranscription
      const transcriptionCall = mockFetch.mock.calls[1]
      expect(JSON.parse(transcriptionCall[1].body)).toMatchObject({
        languageCode: 'es',
      })
    })

    it('uses custom language for summary', async () => {
      mockFetch
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockMetadata),
        })
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockTranscription),
        })
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockSummary),
        })

      await importFromYouTube(`https://www.youtube.com/watch?v=${validVideoId}`, {
        includeSummary: true,
        language: 'en',
      })

      // Third call is summarize
      const summarizeCall = mockFetch.mock.calls[2]
      expect(JSON.parse(summarizeCall[1].body)).toMatchObject({
        language: 'en',
      })
    })

    it('propagates errors from metadata fetch', async () => {
      mockFetch.mockRejectedValueOnce(new Error('Network error'))

      await expect(
        importFromYouTube(`https://www.youtube.com/watch?v=${validVideoId}`)
      ).rejects.toMatchObject({
        code: 'NETWORK_ERROR',
      })
    })

    it('propagates errors from transcription fetch', async () => {
      mockFetch
        .mockResolvedValueOnce({
          ok: true,
          json: () => Promise.resolve(mockMetadata),
        })
        .mockResolvedValueOnce({
          ok: false,
          status: 404,
          json: () => Promise.resolve({ code: 'NO_CAPTIONS', error: 'No captions' }),
        })

      await expect(
        importFromYouTube(`https://www.youtube.com/watch?v=${validVideoId}`)
      ).rejects.toMatchObject({
        code: 'NO_CAPTIONS',
      })
    })
  })

  describe('YouTubeService object', () => {
    it('exports all functions', () => {
      expect(YouTubeService.isAvailable).toBe(isYouTubeImportAvailable)
      expect(YouTubeService.getVideoMetadata).toBe(getVideoMetadata)
      expect(YouTubeService.getCaptionTracks).toBe(getCaptionTracks)
      expect(YouTubeService.getTranscription).toBe(getTranscription)
      expect(YouTubeService.summarizeTranscription).toBe(summarizeTranscription)
      expect(YouTubeService.importFromYouTube).toBe(importFromYouTube)
    })
  })
})
