import type { NoteCategory } from './note'

/**
 * Metadata of a YouTube video
 */
export interface YouTubeVideoMetadata {
  videoId: string
  title: string
  channelName: string
  channelId: string
  thumbnailUrl: string
  duration: string // ISO 8601 duration format (e.g., "PT10M30S")
  publishedAt: string
  viewCount?: string
  description?: string
}

/**
 * A caption track available for a video
 */
export interface YouTubeCaptionTrack {
  id: string
  language: string // Language code (e.g., "en", "es")
  languageName: string // Display name (e.g., "English", "Spanish")
  kind: 'asr' | 'standard' // 'asr' = auto-generated
  isDefault: boolean
}

/**
 * Result of fetching a transcription
 */
export interface TranscriptionResult {
  text: string
  segments?: TranscriptionSegment[]
  language: string
  languageName: string
  isAutoGenerated: boolean
}

/**
 * A segment of the transcription with timing info
 */
export interface TranscriptionSegment {
  start: number // Start time in seconds
  duration: number // Duration in seconds
  text: string
}

/**
 * Result of AI summarization
 */
export interface SummarizationResult {
  summary: string
  keyPoints: string[]
  topics?: string[]
}

/**
 * Options for importing a YouTube video as a note
 */
export interface YouTubeImportOptions {
  includeTranscription: boolean
  includeSummary: boolean
  selectedCaptionTrackId?: string
  targetCategory: NoteCategory
  targetDate: string // YYYY-MM-DD format
}

/**
 * State machine status for YouTube import
 */
export type YouTubeImportStatus =
  | 'idle'
  | 'fetching-metadata'
  | 'fetching-captions'
  | 'summarizing'
  | 'ready'
  | 'creating-note'
  | 'error'

/**
 * Full state of the YouTube import process
 */
export interface YouTubeImportState {
  status: YouTubeImportStatus
  metadata: YouTubeVideoMetadata | null
  captionTracks: YouTubeCaptionTrack[]
  selectedCaptionTrackId: string | null
  transcription: TranscriptionResult | null
  summary: SummarizationResult | null
  error: YouTubeImportError | null
}

/**
 * Error types for YouTube import
 */
export type YouTubeImportErrorCode =
  | 'INVALID_URL'
  | 'VIDEO_NOT_FOUND'
  | 'VIDEO_UNAVAILABLE'
  | 'NO_CAPTIONS'
  | 'CAPTION_FETCH_FAILED'
  | 'SUMMARY_FAILED'
  | 'RATE_LIMITED'
  | 'NOT_CONFIGURED'
  | 'NETWORK_ERROR'
  | 'UNKNOWN_ERROR'

export interface YouTubeImportError {
  code: YouTubeImportErrorCode
  message: string
  retryAfter?: number // For rate limiting
}

/**
 * Initial state for the import process
 */
export const initialYouTubeImportState: YouTubeImportState = {
  status: 'idle',
  metadata: null,
  captionTracks: [],
  selectedCaptionTrackId: null,
  transcription: null,
  summary: null,
  error: null,
}
